#!/bin/bash
#
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
# 
if [[ -e orb1 && -e orb2 && -e orb3 ]]; then
    cat << EOF
You have freed the ring's material form. Add 'ring' to
your inventory. Inscriptions on the ring indicate that it may provide
protection from evil spirits.

export I=ring,\$I

EOF
    exit
else 
    cat << EOF
You try to grasp the faintly glowing ring, but it passes
through your fingers. Maybe reading the scroll will give you a clue.

EOF

fi

printf "Are you stuck? Do you need a hint? y/n  "
read RESP

if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
    cat << EOF
Try searching the lecture notes for how to copy files.

EOF
    printf "Still stuck? Do you need the answer? y/n  "
    read RESP

    if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
        cat << EOF
The cp command copies one file to another. Run these
commands:

cp orb1 orb2
cp orb1 orb3

And then run this ring script again for confirmation.

EOF
    fi
fi


















































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./goblet

